spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cors:
  allowed-origins:
    local: http://localhost:8080
    dev: ${DEV_URL}
    main: ${MAIN_URL}